# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./TransporterAPI
    
jobs:
  build:
    runs-on: ['self-hosted', 'Linux', 'X64', 'main' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: cd ~/actions-runner/deploy/transporterApi/transporterApi/TransporterAPI
    - run: sudo docker container stop transporter-container || true
    - run: sudo docker container stop transporterPostgres || true
    - run: sudo docker container rm transporter-container|| true
    - run: sudo docker image rm transporter || true
    - run: sudo docker build -t transporter .
    - run:  sudo docker container start transporterPostgres || sudo docker run --name transporterPostgres -e POSTGRES_ROOT_PASSWORD=postgres -e POSTGRES_DATABASE=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -d postgres:alpine
    - run: sudo docker run --env-file /home/ubuntu/test.env -p 9090:9090 --name transporter-container --link transporterPostgres:postgres transporter | echo "success" 

 
